#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# postbote setup wizard — walks a human through making postbote ready for
# daily use: link Signal and WhatsApp, build the index, and run the receiving
# daemon as a systemd user unit. Generated with the /wizard skill.
#
# SECURITY RULE — a stage must never break it:
#
#   The QR codes and pairing codes appear in THIS terminal and are nowhere
#   copied, asked for, or stored: they are a secret that binds the device to
#   this machine.
#   (Original: "Die QR-Codes und Kopplungscodes erscheinen in DIESEM Terminal
#   und werden nirgends kopiert, abgefragt oder gespeichert: sie sind ein
#   Geheimnis, das das Geraet an diesen Rechner bindet.")
#
#   A QR is not merely private, it is the credential: whoever scans it owns the
#   linked device, and this terminal is the only place the code ever exists —
#   postbote prints it, the phone consumes it, the screen scrolls it away. So
#   it must never reach a log, a file, a pipe or an agent. These are the code
#   paths that hold that down, and the ones to re-check when a stage changes:
#
#     * A linking command (anything under `pb accounts add`) is invoked only
#       through try()/pb() with stdout and stderr left attached to this
#       terminal. Never wrap one in $(...), a pipeline, a redirection into a
#       file, or a `tee`.
#     * try()'s failure branch prints the label and the exit code, never the
#       command's output.
#     * The one place output is captured anywhere below is verify_unit(), and
#       what it captures is `systemd-analyze` reading a unit FILE this wizard
#       wrote. A unit file is systemd configuration; no linking session is in
#       it and none can be.
#     * Nothing below calls write_env, set_secret or ask_secret, and the
#       library's ENV_FILE is never written: a pairing secret is never
#       persisted. ask() is used only for a filesystem path, which is not a
#       secret and is shown as it is typed.
#
# The library's opening frame says "you drive the browser"; this wizard drives
# a phone. The library is not to be edited to fix that wording.
#
# Overridable, all optional:
#   POSTBOTE_REPO=<path>       a postbote checkout to use instead of detecting
#   POSTBOTE_UNIT_DIR=<path>   where to write the unit (default: the XDG one)
#   POSTBOTE_WIZARD_LIST=1     print the stage titles and exit 0 — lets the
#                              wizard be inspected and tested without a phone,
#                              a session bus or an account
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

STAGE_TITLES=(
  "Readiness: checkout, bundle, live check"
  "Link Signal"
  "Link WhatsApp (optional)"
  "Enable backends — read the terms first"
  "Build the index"
  "Run the daemon in the foreground"
  "Install the systemd user unit"
  "Finish: what runs now, what is left"
)

BUNDLE="app/dist/postbote.gjs.mjs"
SHIPPED_UNIT_REL="contrib/systemd/postbote-daemon.service"
UNIT_NAME="postbote-daemon.service"
# XDG-correct by default; POSTBOTE_UNIT_DIR overrides it, which is also what
# makes this stage testable against a throwaway HOME.
UNIT_DIR="${POSTBOTE_UNIT_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user}"
UNIT="$UNIT_DIR/$UNIT_NAME"
GJSIFY_BIN=""

# _is_checkout DIR — a postbote source tree: the CLI workspace and the
# monorepo root that owns it. A published install has neither.
_is_checkout() {
  [[ -f "$1/app/package.json" && -f "$1/package.json" ]]
}

# _detected_checkout — the tree this wizard ships in, since it lives at
# <checkout>/contrib/setup/. Empty when the file was copied somewhere else.
_detected_checkout() {
  local here up
  here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P) || return 0
  up=$(cd -- "$here/../.." 2>/dev/null && pwd -P) || return 0
  [[ -n "$up" ]] && _is_checkout "$up" && printf '%s' "$up"
}

# _tree_is_at_home_postbote DIR — the repo ships a unit written for a checkout
# at ~/postbote. When that is where the tree really is, the maintained file is
# already correct and beats a generated copy.
_tree_is_at_home_postbote() {
  [[ -d "$HOME/postbote" ]] || return 1
  [[ "$(cd -- "$HOME/postbote" && pwd -P)" == "$(cd -- "$1" && pwd -P)" ]]
}

# write_unit [DEST] writes the receiving daemon's systemd user unit, with this
# machine's real paths. A function rather than inline stage code so it can be
# exercised on its own, without a session bus or an account.
write_unit() {
  local dest="${1:-$UNIT}" wd exec_path unit_path
  if [[ "$MODE" == checkout ]]; then
    wd="$REPO"
    exec_path="$GJSIFY_BIN run $REPO/$BUNDLE daemon"
    unit_path="$(dirname -- "$GJSIFY_BIN"):/usr/local/bin:/usr/bin:/bin"
  else
    # A published install has no tree and no baked bundle path: run the
    # command out of $HOME, where the global bin lives.
    wd="$HOME"
    exec_path="postbote daemon"
    unit_path="%h/.local/bin:/usr/local/bin:/usr/bin:/bin"
  fi
  mkdir -p -- "$(dirname -- "$dest")"
  # The heredoc carries paths and a description. It is not, and must not
  # become, a place a command's output lands — see the security rule above.
  cat >"$dest" <<UNITFILE
# Written by contrib/setup/postbote-setup-wizard.sh. The two paths below are
# this machine's. $SHIPPED_UNIT_REL is the same unit, written for a checkout
# at ~/postbote. Verify: systemd-analyze --user verify <this file>
[Unit]
Description=postbote — receive Signal and WhatsApp into the local index
Documentation=https://github.com/jumplink/postbote/blob/main/docs/adr/0002-receiving-daemon.md
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory=$wd
Environment=PATH=$unit_path
ExecStart=/usr/bin/env $exec_path
Restart=on-failure
RestartPreventExitStatus=2
RestartSec=30
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=default.target
UNITFILE
}

# verify_unit FILE — systemd-analyze on a unit file. The only output captured
# anywhere in this wizard, and it captures a file check, not a session: see
# the security rule above. Returns systemd-analyze's own exit code.
verify_unit() {
  local out rc=0
  out=$(systemd-analyze --user verify "$1" 2>&1) || rc=$?
  printf '%s' "$out"
  return "$rc"
}

# POSTBOTE_WIZARD_LIST=1 — print the stage titles and stop, so the wizard can
# be read and tested where there is no phone, no D-Bus session and no account.
if [[ "${POSTBOTE_WIZARD_LIST:-}" == 1 ]]; then
  printf '%s  postbote setup wizard%s\n' "$BOLD$BLUE" "$RESET"
  printf '%s  %d stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  for _i in "${!STAGE_TITLES[@]}"; do
    printf '  %d. %s\n' "$((_i + 1))" "${STAGE_TITLES[$_i]}"
  done
  printf '\n'
  exit 0
fi

# banner clears the screen, so it has to come before the detection below — a
# word said ahead of it is wiped.
banner "Make postbote ready for daily use"

# ── Which postbote this wizard sets up ────────────────────────────────────
# A checkout runs the built bundle out of its own tree, because the native
# addon path is baked in at build time and a copied tree starts and then dies
# (see AGENTS.md). A published install has no tree and a `postbote` on PATH.
# Detection only ever narrows the options; the human confirms or corrects it.
# This runs AFTER banner, which clears the screen — anything said before it
# would be wiped.
REPO=""
if [[ -n "${POSTBOTE_REPO:-}" ]]; then
  REPO="${POSTBOTE_REPO%/}"
  step "POSTBOTE_REPO: $REPO"
elif _detected=$( _detected_checkout ) && [[ -n "$_detected" ]]; then
  REPO="$_detected"
  step "Found the checkout this wizard ships in: $REPO"
else
  step "No checkout found next to this wizard."
  step "Set POSTBOTE_REPO=/path/to/postbote, or answer the question below."
fi
if [[ -n "$REPO" ]] && ! confirm "Set up this postbote?"; then
  ask REPO "Path of your postbote checkout (empty for a published install):"
  REPO="${REPO%/}"
fi

MODE=""
if [[ -n "$REPO" ]]; then
  if _is_checkout "$REPO"; then
    MODE="checkout"
  else
    warn "No postbote source tree at '$REPO' (app/package.json is missing)."
    REPO=""
  fi
fi
if [[ -z "$MODE" ]] && command -v postbote >/dev/null 2>&1; then
  MODE="published"
  step "Published install: $(command -v postbote)"
fi
if [[ -z "$MODE" ]]; then
  warn "Neither a postbote checkout nor a 'postbote' command on PATH."
  step "Clone the repo, run 'gjsify install', or set POSTBOTE_REPO."
  exit 1
fi

# pb ARGS… runs the postbote this wizard is setting up. It deliberately does
# not capture output: a linking command's output is the QR, and it has to stay
# on this terminal (see the security rule above).
pb() {
  if [[ "$MODE" == checkout ]]; then
    ( cd "$REPO" && gjsify run "$BUNDLE" "$@" )
  else
    postbote "$@"
  fi
}

# try LABEL CMD… runs a command without letting a failure end the wizard. The
# failure branch reports the label and the exit code, never the output.
try() {
  local label="$1"; shift
  if "$@"; then note "$label: ok"
  else warn "$label: exited with $?"; fi
}

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[0]}"
say "This wizard links your devices, builds the index and starts the receiving"
say "daemon as a systemd user unit. You can stop at any time and re-run it."
if [[ "$MODE" == checkout ]]; then
  step "Checkout: $REPO"
  if ! command -v gjsify >/dev/null 2>&1; then
    warn "gjsify is not on PATH. The wizard and the unit both need it."
    step "Install it with: npm install -g @gjsify/cli, then start again."
    exit 1
  fi
  GJSIFY_BIN="$(command -v gjsify)"
  step "gjsify: $GJSIFY_BIN"
  if [[ -f "$REPO/$BUNDLE" ]]; then
    note "Bundle present: $BUNDLE ($(wc -c <"$REPO/$BUNDLE") bytes)"
  else
    step "No bundle yet — building it now, about half a minute."
    try "build" env -C "$REPO/app" npm run build
  fi
  if [[ -f "$REPO/.gjsify-link.json" ]]; then
    note "gjsify is linked to a local checkout, so you run untagged fixes."
  else
    warn "No gjsify link: postbote runs against the published version."
  fi
else
  step "Published install: $(command -v postbote)"
  note "No build step and no checkout: the installed command is used as it is."
fi
step "Live check (reads your online accounts, writes nothing):"
try "check" pb check
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[1]}"
say "postbote registers itself with your phone as a linked device. The QR code"
say "appears below, in this terminal."
step "On the phone: Signal → Settings → Linked devices → Link new device."
note "The QR code and every pairing code are a secret: do not copy, paste or"
note "send any of them. It binds your account to this machine."
if confirm "Link Signal now?"; then
  try "accounts add signal" pb accounts add signal
else
  note "skipped"
fi
step "Accounts the backend knows now (count only):"
try "accounts list" pb accounts list --backend signal
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[2]}"
say "Same flow: a QR code in the terminal, or type the pairing code shown here"
say "into the phone if the code does not read there as an image."
note "Same rule as before — the pairing code is a secret, it goes nowhere else."
if confirm "Link WhatsApp now?"; then
  try "accounts add whatsapp" pb accounts add whatsapp
  try "accounts list" pb accounts list --backend whatsapp
else
  note "skipped"
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[3]}"
say "The daemon only receives what is enabled here. The first enable prints a"
say "terms notice — read it yourself before you accept it."
step "Current state:"
try "backends list" pb backends list
for _be in signal whatsapp; do
  # Ask, do not infer. `accounts list --backend <name>` exits 0 with an empty
  # list for a backend that was never linked — asking about an unlinked account
  # changes nothing on disk — so an exit code cannot say whether the phone
  # accepted the QR. Only the person holding it knows that. The listing is
  # printed, not silenced: account ids are not secret, and seeing them is how
  # the answer becomes obvious. Never do this to `accounts add` — that is the
  # QR, and it stays on this terminal.
  step "Accounts $_be knows about:"
  try "accounts list" pb accounts list --backend "$_be"
  if confirm "Is $_be linked — did you scan its QR code with the phone?"; then
    step "Showing the terms for $_be (no --accept-terms):"
    try "terms $_be" pb backends enable "$_be"
    if confirm "Read the terms for $_be and accept them?"; then
      try "enable $_be" pb backends enable "$_be" --accept-terms
    else
      note "$_be stays disabled"
    fi
  else
    note "$_be not linked — leaving it disabled. Link it in stage 2 or 3 first."
  fi
done
try "backends list" pb backends list
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[4]}"
say "postbote searches the local index, not the network. Only 'sync' writes it."
say "It reads the headers of your mail accounts, never a body."
step "With many accounts this takes a few minutes."
if confirm "Build the index now?"; then
  try "sync" pb sync
else
  note "skipped — 'postbote conversations' stays empty until you do"
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[5]}"
say "The daemon receives in the background without walking the index. Leave it"
say "30 to 60 seconds, then stop it with Ctrl-C."
note "Expect one line per account as it connects, account ids rather than"
note "phone numbers, and exit 0 when you stop it."
if confirm "Start the daemon now?"; then
  step "Ctrl-C stops it. Do that yourself once the accounts are connected."
  pb daemon || warn "daemon exited with $?"
else
  note "skipped"
fi
step "What the daemon received (count only):"
try "deliveries" pb deliveries
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[6]}"
say "This runs the daemon without a terminal and starts it with your session."
# The unit in the repo is written for a checkout at ~/postbote. When that is
# where this tree actually is, the maintained file is already correct and beats
# a generated copy; otherwise the paths below have to be this machine's.
if [[ "$MODE" == checkout ]] && [[ -f "$REPO/$SHIPPED_UNIT_REL" ]] \
   && _tree_is_at_home_postbote "$REPO"; then
  say "Your checkout IS ~/postbote, so $SHIPPED_UNIT_REL already names the"
  say "right paths (%h/postbote). Installing it unchanged is the better deal."
  if confirm "Install the shipped unit unchanged?"; then
    mkdir -p -- "$UNIT_DIR"
    cp -- "$REPO/$SHIPPED_UNIT_REL" "$UNIT"
    note "installed unchanged: $REPO/$SHIPPED_UNIT_REL → $UNIT"
  else
    say "Writing the same paths myself instead."
    write_unit
    note "written: $UNIT"
  fi
else
  if [[ "$MODE" == checkout ]]; then
    say "The unit in the repo assumes the tree lives at ~/postbote; yours is at"
    say "$REPO, so the paths below are this machine's."
  fi
  write_unit
  note "written: $UNIT"
fi
step "Verifying it (no output and exit 0 means it is clean):"
if verify_unit "$UNIT"; then
  note "systemd-analyze --user verify: exit 0, no findings"
else
  warn "systemd-analyze --user verify: exit $? — the findings are above"
fi
if confirm "Enable and start the unit now?"; then
  systemctl --user daemon-reload
  systemctl --user enable --now "$UNIT_NAME"
  sleep 3
  try "status" systemctl --user --no-pager --lines=8 status "$UNIT_NAME"
  step "When in doubt: journalctl --user -u postbote-daemon -f"
  note "Exit 2 means every account is logged out. The unit then stays failed on"
  note "purpose and does not restart. After linking again:"
  note "  systemctl --user restart postbote-daemon"
  note "Without a session, the unit still needs: loginctl enable-linger \"$USER\""
else
  note "skipped — the unit is written but not enabled"
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "${STAGE_TITLES[7]}"
say "What runs now, and what is left to do."
step "Accounts:";       try "accounts" pb accounts list
step "Daemon:";         try "status" systemctl --user --no-pager --lines=0 is-active "$UNIT_NAME"
step "Received:";       try "deliveries" pb deliveries
step "Conversations:";  try "conversations" pb conversations
cat <<NOTE

  Keep going on your own:
   • Back up \$XDG_DATA_HOME/postbote/config.json and index.db. With WhatsApp
     or Signal enabled the index is irreplaceable — those networks keep no
     archive — and the session files under secrets/ are secrets: back them up
     like a password, never share them.
   • loginctl enable-linger "\$USER" so the daemon also runs while you are
     logged out; that is what lets a user unit run at all without a session.
   • Check the daemon after a few days: postbote deliveries, or
     journalctl --user -u postbote-daemon. A unit sitting at exit 2 means
     every account was logged out — relink, then restart it.
   • End a linked device from the phone (Settings → Linked devices). Deleting
     the session file under secrets/ ends it on this machine.
   • A sync from a timer is the fallback for a machine where the daemon does
     not run — but not both at once: they take a lease on the same accounts.
NOTE
pause

finish
